### ISSUE TITLE
plain slide

### ISSUE THREAD

**Issue by manuelreif** [pat-s/xaringan-metropolis#1]
Hi!

I am using your theme with the xaringan package and I am a total css noob. So my question is: is there a possibility with your theme to add a "plain" slide (like in LaTeX) without any header bar (not title - just white background)? This would be quite useful for displaying interactive graphs on total screen.

Thank you so much!
Manuel

**Comment by pat-s** [comment]
Hi Manuel,

great to hear that you enjoy it!

I added a new class so you can just use `class: clear` now for the specific slide with the most recent version of the theme.

**Comment by manuelreif** [comment]
Thanks for your work!
Works like charm!!
