### ISSUE TITLE
logo on title slide and on header

### ISSUE THREAD

**Issue by claudiofronterre** [pat-s/xaringan-metropolis#4]
Hello,

First of all thank you for this wonderful contribution to xaringan.

I was wondering if there is a way to add a logo to the title slide and to the header (left to the title of each slide).

I have been trying to define a new header and then add a logo but the result is horrible.

Many thanks!

**Comment by pat-s** [comment]
Hi, 

great that you like it.
The question is not theme-specific and would fit better to the `xaringan` main repo.

Have you already taken a look at this [SO post](https://stackoverflow.com/questions/48976338/how-can-i-modifiy-the-positions-of-the-text-and-logo-on-rmarkdown-title-slide/49018455#49018455)?

**Comment by claudiofronterre** [comment]
Hi Patrick,

No I did not see it. Turns out to be very useful.

Many thanks!
